# Generated by Django 5.2.3 on 2025-06-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EverydayCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('name', models.CharField(help_text='Nome da categoria do cotidiano', max_length=100, unique=True, verbose_name='Nome da categoria')),
            ],
            options={
                'verbose_name': 'Categoria do Cotidiano',
                'verbose_name_plural': 'Categorias do Cotidiano',
                'ordering': ['name'],
            },
        ),
    ]
