# Generated by Django 5.2.3 on 2025-06-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_caa', '0002_everydaycategory_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='everydaycategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo'),
        ),
    ]
