# Generated by Django 5.2.3 on 2025-06-24 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_caa', '0003_everydaycategory_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo')),
                ('name', models.CharField(help_text='Nome descritivo do pictograma', max_length=100, verbose_name='Nome do pictograma')),
                ('image', models.ImageField(help_text='Arquivo de imagem do pictograma (PNG, JPG, etc.)', upload_to='pictograms/images/', verbose_name='Imagem do pictograma')),
                ('audio', models.FileField(blank=True, help_text='Arquivo de áudio com a pronúncia do pictograma (MP3, WAV, etc.)', null=True, upload_to='pictograms/audio/', verbose_name='Áudio do pictograma')),
                ('description', models.TextField(blank=True, help_text='Descrição adicional do pictograma', null=True, verbose_name='Descrição')),
                ('category', models.ForeignKey(help_text='Categoria do cotidiano à qual o pictograma pertence', on_delete=django.db.models.deletion.CASCADE, related_name='pictograms', to='smart_caa.everydaycategory', verbose_name='Categoria')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Pictograma',
                'verbose_name_plural': 'Pictogramas',
                'ordering': ['name'],
                'unique_together': {('name', 'category')},
            },
        ),
    ]
