# Generated by Django 5.2.3 on 2025-06-25 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_caa', '0004_pictogram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo')),
                ('name', models.CharField(help_text='Nome completo da pessoa', max_length=200, verbose_name='Nome completo')),
                ('cpf', models.CharField(help_text='CPF da pessoa (formato: 000.000.000-00)', max_length=14, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(help_text='Endereço de e-mail da pessoa', max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(help_text='Número de telefone ou celular', max_length=20, verbose_name='Contato')),
                ('address', models.TextField(help_text='Endereço completo da pessoa', verbose_name='Endereço')),
                ('is_patient', models.BooleanField(default=False, help_text='Indica se a pessoa é um paciente', verbose_name='É Paciente')),
                ('is_caregiver', models.BooleanField(default=False, help_text='Indica se a pessoa é um cuidador', verbose_name='É Cuidador')),
                ('colors', models.TextField(blank=True, help_text='Cores que o paciente gosta ou tem preferência', null=True, verbose_name='Cores')),
                ('sounds', models.TextField(blank=True, help_text='Sons, toques ou músicas que o paciente aprecia', null=True, verbose_name='Toques')),
                ('smells', models.TextField(blank=True, help_text='Cheiros que o paciente gosta ou reconhece', null=True, verbose_name='Cheiros')),
                ('hobbies', models.TextField(blank=True, help_text='Atividades e hobbies do paciente', null=True, verbose_name='Hobbies')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['name'],
            },
        ),
    ]
