# Generated by Django 5.2.3 on 2025-06-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_caa', '0005_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(help_text='Endereço de e-mail da pessoa', max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(help_text='Número de telefone ou celular', max_length=20, unique=True, verbose_name='Contato'),
        ),
    ]
