# Generated by Django 5.2.3 on 2025-06-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_caa', '0006_alter_person_email_alter_person_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
    ]
