# Generated by Django 5.2.3 on 2025-06-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_caa', '0007_remove_person_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, help_text='Nome da cidade', max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='person',
            name='complement',
            field=models.CharField(blank=True, help_text='Apartamento, bloco, casa, etc.', max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='person',
            name='district',
            field=models.CharField(blank=True, help_text='Nome do bairro', max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='person',
            name='number',
            field=models.CharField(blank=True, help_text='Número da residência/estabelecimento', max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='person',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Código de Endereçamento Postal (formato: 00000-000)', max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='person',
            name='state',
            field=models.CharField(blank=True, help_text='Unidade Federativa (Estado)', max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='person',
            name='street',
            field=models.CharField(blank=True, help_text='Rua, avenida, travessa, etc.', max_length=200, null=True, verbose_name='Logradouro'),
        ),
    ]
