# Generated by Django 5.2.3 on 2025-07-05 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_caa', '0008_person_city_person_complement_person_district_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='everydaycategory',
            name='inactivated_at',
            field=models.DateTimeField(blank=True, help_text='Data em que o registro foi inativado', null=True, verbose_name='Data de inativação'),
        ),
        migrations.AddField(
            model_name='everydaycategory',
            name='inactivated_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que inativou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_inactivated', to=settings.AUTH_USER_MODEL, verbose_name='Inativado por'),
        ),
        migrations.AddField(
            model_name='person',
            name='inactivated_at',
            field=models.DateTimeField(blank=True, help_text='Data em que o registro foi inativado', null=True, verbose_name='Data de inativação'),
        ),
        migrations.AddField(
            model_name='person',
            name='inactivated_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que inativou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_inactivated', to=settings.AUTH_USER_MODEL, verbose_name='Inativado por'),
        ),
        migrations.AddField(
            model_name='pictogram',
            name='inactivated_at',
            field=models.DateTimeField(blank=True, help_text='Data em que o registro foi inativado', null=True, verbose_name='Data de inativação'),
        ),
        migrations.AddField(
            model_name='pictogram',
            name='inactivated_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que inativou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_inactivated', to=settings.AUTH_USER_MODEL, verbose_name='Inativado por'),
        ),
        migrations.CreateModel(
            name='PatientCaregiverRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo')),
                ('inactivated_at', models.DateTimeField(blank=True, help_text='Data em que o registro foi inativado', null=True, verbose_name='Data de inativação')),
                ('relationship_type', models.CharField(choices=[('FAMILY', 'Familiar'), ('PROFESSIONAL', 'Profissional'), ('FRIEND', 'Amigo'), ('VOLUNTEER', 'Voluntário'), ('OTHER', 'Outros')], help_text='Tipo de relacionamento entre paciente e cuidador', max_length=20, verbose_name='Tipo de Vínculo')),
                ('start_date', models.DateField(help_text='Data de início do vínculo entre paciente e cuidador', verbose_name='Data de Início')),
                ('notes', models.TextField(blank=True, help_text='Observações sobre o relacionamento', null=True, verbose_name='Observações')),
                ('caregiver', models.ForeignKey(help_text='Pessoa que é cuidador neste relacionamento', limit_choices_to={'is_caregiver': True}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_relationships', to='smart_caa.person', verbose_name='Cuidador')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('inactivated_by', models.ForeignKey(blank=True, help_text='Usuário que inativou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_inactivated', to=settings.AUTH_USER_MODEL, verbose_name='Inativado por')),
                ('patient', models.ForeignKey(help_text='Pessoa que é paciente neste relacionamento', limit_choices_to={'is_patient': True}, on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_relationships', to='smart_caa.person', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Relacionamento Paciente-Cuidador',
                'verbose_name_plural': 'Relacionamentos Paciente-Cuidador',
                'ordering': ['-start_date', 'patient__name', 'caregiver__name'],
                'unique_together': {('patient', 'caregiver')},
            },
        ),
    ]
