# Generated by Django 5.2.3 on 2025-07-05 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_caa', '0009_everydaycategory_inactivated_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patientcaregiverrelationship',
            unique_together=set(),
        ),
    ]
