# Generated by Django 5.2.3 on 2025-07-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_caa', '0010_alter_patientcaregiverrelationship_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cid',
            field=models.CharField(blank=True, help_text='Classificação Internacional de Doenças (formato: A00-B99, C00-D48)', max_length=20, null=True, verbose_name='CID'),
        ),
    ]
