# Generated by Django 5.2.3 on 2025-07-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_caa', '0011_person_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profession',
            field=models.CharField(blank=True, help_text='Profissão ou ocupação da pessoa', max_length=100, null=True, verbose_name='Profissão'),
        ),
    ]
