# Generated by Django 5.2.4 on 2025-07-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_caa', '0013_person_user_alter_everydaycategory_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictogram',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Se marcado, este pictograma será automaticamente vinculado a novos pacientes', verbose_name='Pictograma padrão'),
        ),
    ]
