# Generated by Django 5.2.3 on 2025-07-11 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_caa', '0014_pictogram_is_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPictogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo')),
                ('inactivated_at', models.DateTimeField(blank=True, help_text='Data em que o registro foi inativado', null=True, verbose_name='Data de inativação')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('inactivated_by', models.ForeignKey(blank=True, help_text='Usuário que inativou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_inactivated', to=settings.AUTH_USER_MODEL, verbose_name='Inativado por')),
                ('patient', models.ForeignKey(help_text='Paciente ao qual o pictograma será vinculado', limit_choices_to={'is_patient': True}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_pictograms', to='smart_caa.person', verbose_name='Paciente')),
                ('pictogram', models.ForeignKey(help_text='Pictograma vinculado ao paciente', on_delete=django.db.models.deletion.CASCADE, related_name='patient_pictograms', to='smart_caa.pictogram', verbose_name='Pictograma')),
            ],
            options={
                'verbose_name': 'Pictograma do Paciente',
                'verbose_name_plural': 'Pictogramas dos Pacientes',
                'ordering': ['patient__name', 'pictogram__name', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'is_active'], name='smart_caa_p_patient_e78d2d_idx'), models.Index(fields=['pictogram', 'is_active'], name='smart_caa_p_pictogr_3ac4a1_idx'), models.Index(fields=['patient', 'pictogram', 'is_active'], name='smart_caa_p_patient_6fec1a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('patient', 'pictogram'), name='unique_active_patient_pictogram', violation_error_message='Este pictograma já está ativo para este paciente.')],
            },
        ),
    ]
