# Generated by Django 5.2.5 on 2025-08-29 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_caa', '0015_patientpictogram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo')),
                ('inactivated_at', models.DateTimeField(blank=True, help_text='Data em que o registro foi inativado', null=True, verbose_name='Data de inativação')),
                ('main_diagnosis', models.CharField(blank=True, help_text='Diagnóstico médico principal do paciente', max_length=200, null=True, verbose_name='Diagnóstico Principal')),
                ('associated_conditions', models.TextField(blank=True, help_text='Outras condições médicas ou comorbidades', null=True, verbose_name='Condições Associadas')),
                ('allergies', models.TextField(blank=True, help_text='Alergias conhecidas do paciente', null=True, verbose_name='Alergias')),
                ('medications', models.TextField(blank=True, help_text='Medicamentos em uso atual', null=True, verbose_name='Medicações')),
                ('communication_methods', models.TextField(blank=True, help_text='Métodos de comunicação utilizados pelo paciente', null=True, verbose_name='Formas de Comunicação')),
                ('spoken_words', models.TextField(blank=True, help_text='Palavras que o paciente consegue falar ou entender', null=True, verbose_name='Palavras Faladas')),
                ('preferred_pictograms', models.TextField(blank=True, help_text='Pictogramas ou símbolos que o paciente prefere ou reconhece melhor', null=True, verbose_name='Pictogramas Preferidos')),
                ('dietary_restrictions', models.TextField(blank=True, help_text='Alimentos que devem ser evitados ou restrições específicas', null=True, verbose_name='Restrições Alimentares')),
                ('food_preferences', models.TextField(blank=True, help_text='Alimentos favoritos ou preferências do paciente', null=True, verbose_name='Preferências Alimentares')),
                ('feeding_difficulties', models.TextField(blank=True, help_text='Problemas ou dificuldades relacionadas à alimentação', null=True, verbose_name='Dificuldades na Alimentação')),
                ('needs_expression', models.TextField(blank=True, help_text='Como o paciente expressa suas necessidades e desejos', null=True, verbose_name='Expressão de Necessidades')),
                ('frustration_reactions', models.TextField(blank=True, help_text='Como o paciente reage quando frustrado ou irritado', null=True, verbose_name='Reações à Frustração')),
                ('general_observations', models.TextField(blank=True, help_text='Observações adicionais importantes sobre o paciente', null=True, verbose_name='Observações Gerais')),
                ('caregiver', models.ForeignKey(blank=True, help_text='Cuidador que cadastrou a anamnese', limit_choices_to={'is_caregiver': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_anamneses', to='smart_caa.person', verbose_name='Cuidador')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('inactivated_by', models.ForeignKey(blank=True, help_text='Usuário que inativou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_inactivated', to=settings.AUTH_USER_MODEL, verbose_name='Inativado por')),
                ('patient', models.ForeignKey(help_text='Paciente para quem a anamnese foi criada', limit_choices_to={'is_patient': True}, on_delete=django.db.models.deletion.CASCADE, related_name='anamneses', to='smart_caa.person', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Anamnese',
                'verbose_name_plural': 'Anamneses',
                'ordering': ['-created_at'],
                'unique_together': {('patient', 'caregiver')},
            },
        ),
    ]
