# Generated by Django 5.2.3 on 2026-03-25 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_caa', '0016_anamnesis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo')),
                ('inactivated_at', models.DateTimeField(blank=True, help_text='Data em que o registro foi inativado', null=True, verbose_name='Data de inativação')),
                ('description', models.TextField(help_text='Descrição do histórico', verbose_name='Descrição')),
                ('caregiver', models.ForeignKey(help_text='Pessoa que é cuidador no histórico', limit_choices_to={'is_caregiver': True}, on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_histories', to='smart_caa.person', verbose_name='Cuidador')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('inactivated_by', models.ForeignKey(blank=True, help_text='Usuário que inativou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_inactivated', to=settings.AUTH_USER_MODEL, verbose_name='Inativado por')),
                ('patient', models.ForeignKey(help_text='Pessoa que é paciente no histórico', limit_choices_to={'is_patient': True}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_histories', to='smart_caa.person', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Histórico',
                'verbose_name_plural': 'Históricos',
                'ordering': ['-created_at', 'patient__name', 'caregiver__name'],
            },
        ),
    ]
