# Generated by Django 5.2.3 on 2026-03-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_caa', '0017_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictogram',
            name='private',
            field=models.BooleanField(default=False, help_text='Se marcado esse pictograma será disponibilizado apenas para o paciente que foi vinculado a ele', verbose_name='Privado para um paciente'),
        ),
    ]
