# Generated by Django 5.2.3 on 2026-03-28 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_caa', '0018_pictogram_private'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo')),
                ('inactivated_at', models.DateTimeField(blank=True, help_text='Data em que o registro foi inativado', null=True, verbose_name='Data de inativação')),
                ('name', models.CharField(help_text='Nome descritivo do anexo', max_length=255, verbose_name='Nome do Anexo')),
                ('file', models.FileField(help_text='Arquivo anexado (imagem, PDF, etc.)', upload_to='anexos/', verbose_name='Arquivo do Anexo')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('inactivated_by', models.ForeignKey(blank=True, help_text='Usuário que inativou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_inactivated', to=settings.AUTH_USER_MODEL, verbose_name='Inativado por')),
                ('patient', models.ForeignKey(help_text='Paciente ao qual o anexo pertence', limit_choices_to={'is_patient': True}, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='smart_caa.person', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['-created_at'],
            },
        ),
    ]
