# Generated by Django 5.2.3 on 2026-04-10 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_caa', '0019_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='history',
            field=models.ForeignKey(blank=True, help_text='Histórico ao qual o anexo pode estar vinculado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='smart_caa.history', verbose_name='Histórico'),
        ),
    ]
