# Generated by Django 5.2.3 on 2026-04-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_caa', '0020_attachment_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnesis',
            name='attention_duration',
            field=models.CharField(blank=True, help_text='Tempo ou nível de atenção/concentração do paciente', max_length=100, null=True, verbose_name='Atenção / Concentração'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='auditory_comprehension',
            field=models.CharField(blank=True, help_text='O quanto o paciente compreende comandos, palavras ou frases', max_length=150, null=True, verbose_name='Compreensão Auditiva'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Data de nascimento informada na ficha de anamnese', null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='cognitive_level',
            field=models.CharField(blank=True, help_text='Nível cognitivo estimado do paciente', max_length=100, null=True, verbose_name='Nível Cognitivo'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='communication_priorities',
            field=models.TextField(blank=True, help_text='Principais necessidades comunicativas do paciente', null=True, verbose_name='Necessidades Comunicativas Principais'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='expressive_vocabulary',
            field=models.CharField(blank=True, help_text='Estimativa do vocabulário expressivo atual do paciente', max_length=100, null=True, verbose_name='Vocabulário Expressivo'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='functional_speech',
            field=models.CharField(blank=True, help_text='Ex.: não, sim parcial ou sim completa', max_length=100, null=True, verbose_name='Possui Fala Funcional'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='gender',
            field=models.CharField(blank=True, help_text='Gênero do paciente informado na ficha', max_length=50, null=True, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='language_style',
            field=models.CharField(blank=True, help_text='Forma predominante de compreensão da linguagem pelo paciente', max_length=50, null=True, verbose_name='Linguagem Literal ou Figurada'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='learning_pace',
            field=models.CharField(blank=True, help_text='Velocidade ou facilidade de aprendizado do paciente', max_length=100, null=True, verbose_name='Capacidade de Aprendizado'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='memory_profile',
            field=models.CharField(blank=True, help_text='Perfil de memória visual e/ou auditiva do paciente', max_length=150, null=True, verbose_name='Memória'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='preferred_symbol_systems',
            field=models.TextField(blank=True, help_text='Ex.: PCS, Bliss, Arasaac, fotografias, desenhos', null=True, verbose_name='Sistemas de Símbolos Preferidos'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='previous_caa_experience',
            field=models.TextField(blank=True, help_text='Histórico de uso anterior de recursos de comunicação alternativa e ampliada', null=True, verbose_name='Experiência Prévia com CAA'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='reference_professional',
            field=models.CharField(blank=True, help_text='Profissional que acompanha o paciente, como fonoaudiólogo ou terapeuta', max_length=200, null=True, verbose_name='Profissional de Referência'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='responsible_contact',
            field=models.CharField(blank=True, help_text='Telefone, e-mail ou outro contato do responsável/cuidador', max_length=200, null=True, verbose_name='Contato do Responsável'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='specific_difficulties',
            field=models.TextField(blank=True, help_text='Dificuldades cognitivas específicas observadas', null=True, verbose_name='Dificuldades Específicas'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='speech_intelligibility',
            field=models.CharField(blank=True, help_text='Nível de inteligibilidade da fala do paciente', max_length=100, null=True, verbose_name='Inteligibilidade de Fala'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='symbol_comprehension',
            field=models.CharField(blank=True, help_text='Nível de compreensão dos símbolos apresentados', max_length=100, null=True, verbose_name='Compreensão de Símbolos'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='uses_gestures',
            field=models.BooleanField(blank=True, help_text='Indica se o paciente utiliza gestos naturais para se comunicar', null=True, verbose_name='Usa Gestos'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='uses_images_or_symbols',
            field=models.BooleanField(blank=True, help_text='Indica se já utiliza comunicação por imagens, figuras ou símbolos', null=True, verbose_name='Usa Imagens ou Símbolos'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='uses_signs',
            field=models.BooleanField(blank=True, help_text='Indica se o paciente utiliza Libras ou outro sistema de sinais', null=True, verbose_name='Usa Sinais'),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='associated_conditions',
            field=models.TextField(blank=True, help_text='Comorbidades ou diagnósticos secundários relacionados ao paciente', null=True, verbose_name='Comorbidades / Diagnósticos Secundários'),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='main_diagnosis',
            field=models.CharField(blank=True, help_text='Diagnóstico principal do paciente', max_length=200, null=True, verbose_name='Diagnóstico Principal'),
        ),
    ]
