# Generated by Django 5.2.3 on 2026-04-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_caa', '0021_anamnesis_attention_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamnesis',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='anamnesis',
            name='gender',
        ),
    ]
