# Generated by Django 5.2.3 on 2026-04-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_caa', '0022_remove_anamnesis_birth_date_remove_anamnesis_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamnesis',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='anamnesis',
            name='medications',
        ),
    ]
