# Generated by Django 5.2.3 on 2026-04-11 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_caa', '0023_remove_anamnesis_allergies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamnesis',
            name='specific_difficulties',
        ),
    ]
