# Generated by Django 5.2.3 on 2026-04-11 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_caa', '0024_remove_anamnesis_specific_difficulties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamnesis',
            name='communication_methods',
        ),
        migrations.RemoveField(
            model_name='anamnesis',
            name='dietary_restrictions',
        ),
        migrations.RemoveField(
            model_name='anamnesis',
            name='expressive_vocabulary',
        ),
        migrations.RemoveField(
            model_name='anamnesis',
            name='feeding_difficulties',
        ),
        migrations.RemoveField(
            model_name='anamnesis',
            name='food_preferences',
        ),
        migrations.RemoveField(
            model_name='anamnesis',
            name='frustration_reactions',
        ),
        migrations.RemoveField(
            model_name='anamnesis',
            name='general_observations',
        ),
        migrations.RemoveField(
            model_name='anamnesis',
            name='needs_expression',
        ),
        migrations.RemoveField(
            model_name='anamnesis',
            name='preferred_pictograms',
        ),
        migrations.RemoveField(
            model_name='anamnesis',
            name='previous_caa_experience',
        ),
        migrations.RemoveField(
            model_name='anamnesis',
            name='spoken_words',
        ),
    ]
