# Generated by Django 5.2.3 on 2026-04-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_caa', '0025_remove_anamnesis_communication_methods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Data de nascimento da pessoa', null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], help_text='Gênero informado no cadastro: Masculino ou Feminino', max_length=10, null=True, verbose_name='Gênero'),
        ),
    ]
