# Generated by Django 5.2.3 on 2026-03-29 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo')),
                ('inactivated_at', models.DateTimeField(blank=True, help_text='Data em que o registro foi inativado', null=True, verbose_name='Data de inativação')),
                ('name', models.CharField(help_text='Nome do tipo de conta', max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, help_text='Descrição do tipo de conta', verbose_name='Descrição')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('inactivated_by', models.ForeignKey(blank=True, help_text='Usuário que inativou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_inactivated', to=settings.AUTH_USER_MODEL, verbose_name='Inativado por')),
            ],
            options={
                'verbose_name': 'Tipo de Conta',
                'verbose_name_plural': 'Tipos de Conta',
                'ordering': ['name'],
            },
        ),
    ]
