# Generated by Django 5.2.3 on 2026-03-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_paymentplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='attachments_per_patient',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade máxima de anexos por paciente', verbose_name='Qtd. anexos por paciente'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='custom_pictograms_per_patient',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade máxima de pictogramas personalizados por paciente', verbose_name='Qtd. pictogramas personalizados por paciente'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='user_limit',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade máxima de usuários permitidos no plano', verbose_name='Quantidade de usuários'),
        ),
    ]
