# Generated by Django 5.2.3 on 2026-03-29 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_paymentplan_attachments_per_patient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo')),
                ('inactivated_at', models.DateTimeField(blank=True, help_text='Data em que o registro foi inativado', null=True, verbose_name='Data de inativação')),
                ('name', models.CharField(help_text='Nome da conta', max_length=100, verbose_name='Nome da conta')),
                ('due_day', models.PositiveSmallIntegerField(help_text='Dia do mês para vencimento da cobrança', verbose_name='Dia do vencimento')),
                ('start_date', models.DateField(help_text='Data de início da conta', verbose_name='Data de início')),
                ('first_due_date', models.DateField(help_text='Data do primeiro vencimento da conta', verbose_name='Data do 1º vencimento')),
                ('end_date', models.DateField(blank=True, help_text='Data de término da vigência da conta', null=True, verbose_name='Data fim vigência')),
                ('responsible_name', models.CharField(help_text='Nome do responsável pela conta', max_length=100, verbose_name='Nome do responsável')),
                ('responsible_phone', models.CharField(help_text='Celular do responsável pela conta', max_length=20, verbose_name='Celular do responsável')),
                ('responsible_email', models.EmailField(help_text='E-mail do responsável pela conta', max_length=254, verbose_name='E-mail do responsável')),
                ('auto_renewal', models.BooleanField(default=False, help_text='Se a conta possui renovação automática', verbose_name='Renovação automática')),
                ('description', models.TextField(blank=True, help_text='Descrição adicional da conta', verbose_name='Descrição')),
                ('account_type', models.ForeignKey(help_text='Tipo de conta associada', on_delete=django.db.models.deletion.PROTECT, to='management.accounttype', verbose_name='Tipo de Conta')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('inactivated_by', models.ForeignKey(blank=True, help_text='Usuário que inativou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_inactivated', to=settings.AUTH_USER_MODEL, verbose_name='Inativado por')),
                ('payment_period', models.ForeignKey(help_text='Período de pagamento da conta', on_delete=django.db.models.deletion.PROTECT, to='management.paymentperiod', verbose_name='Período de Pagamento')),
                ('payment_plan', models.ForeignKey(help_text='Plano de pagamento da conta', on_delete=django.db.models.deletion.PROTECT, to='management.paymentplan', verbose_name='Plano de Pagamento')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'ordering': ['name'],
            },
        ),
    ]
